[workspace]
resolver = "3"
members = [
    "abd",
    "abd-bench",
    "abd-example",
	"echo",
	"echo-example",
	"echo-trivial",
	"specs",
	"verdist",
    "vlib",
]
exclude = ["../verus/source/vstd"]

[workspace.package]
version = "0.0.0"
license = "MIT"
edition = "2024"
rust-version = "1.95"
repository = "https://github.com/bsdinis/verdist"

[workspace.dependencies]
clap = { version = "4.4.12", features = ["derive"] }
crossbeam-channel = "0.5.15"
flexbuffers = "25.12"
humantime = "2.4.0"
io-uring = "0.7"
libc = "0.2"
mio = { version = "1.2.2", features = ["os-poll", "os-ext"] }
polars = { version = "0.53", features = ["lazy"] }
rand = "0.10.1"
rand_distr = "0.6.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"

abd = { path = "./abd" }
echo = { path = "./echo" }
specs = { path = "./specs" }
verdist = { path = "./verdist" }
vlib = { path = "./vlib" }
vstd = { path = "../verus/source/vstd" }

[workspace.lints.clippy]
explicit_iter_loop = "warn"
flat_map_option = "warn"
implicit_clone = "warn"
needless_for_each = "warn"
semicolon_if_nothing_returned = "warn"
uninlined_format_args = "warn"
useless_conversion = "warn"
semicolon-if-nothing-returned = "allow"


[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(verus_only)', 'cfg(verus_keep_ghost_body)', 'cfg(verus_keep_ghost)'] }

[profile.release]
strip = "debuginfo"

