[package]
name = "abd-example"

edition = { workspace = true }
license = { workspace = true }
readme = "README.md"
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[dependencies]
clap = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }

abd = { workspace = true }
specs = { workspace = true }
verdist = { workspace = true }
vlib = { workspace = true }
vstd = { workspace = true }

[lints]
workspace = true

[lib]
name = "abd_example"
path = "src/lib.rs"

[[bin]]
name = "abd_client"
path = "src/client.rs"

[[bin]]
name = "abd_server"
path = "src/server.rs"

[package.metadata.verus]
verify = true
